### ISSUE TITLE
Update README to accurately represent the current state of the code

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/LabLib#16]
#### Description:

The README appears outdated and doesn't accurately represent the current state of the code. We need to explain to potential community users how to utilize the package, test it, and contribute effectively.

#### Tasks:

- [ ]     Update README with clear instructions on how to utilize the package
- [ ]     Include guidelines for testing the package
- [ ]     Add information on how to contribute effectively to the project

#### Additional Information:

Feel free to provide any additional context or details related to this issue.

**Comment by tweak-wtf** [comment]
yes! we should also state somewhere that currently this is only tested on windows.
